adobe/helix-rum-collector

.circleci/config.yml
.releaserc.js
package.json

- ci(deploy): add branch deploy workflow
- ci(deploy): add circleci context
- ci(deploy): pass fastly token
- build(package): allow bundle to run on bsd tar and gnu tar
- build(package): create pkg directory if it does not exist
- ci(deploy): deploy to fastly using correct credentials
- build(eslint): add eslint config
- test(post-deploy): add post-deploy tests
- style(test): eslint formatting
- test(post-deploy): fix test path
- ci(deploy): deploy to prod using semantic-release

branch deploy

---

as-pect.config.js
package-lock.json
package.json

- build(deps): remove unused dotenv dependency
- build(deps): bump eslint
- build(deps): bump eslint-plugin-import
- build(deps): remove unused dependency jsdom
- build(deps): bump mocha
- build(deps): bump semantic-release
- build(deps): remove unused dependency fs-extra
- build(deps): remove unused dependency yargs
- build(deps): remove unused dependency puppeteer
- fix(deps): bump assembly-script-related dependencies

wasm update

---

assembly/index.ts
test/js/post-deploy.test.js

Relax the API and allow `cwv` to be omitted

feat: allow cwv to be omitted

---

.github/workflows/cleanup-fastly.yml

our current ci process creates one fastly service for each branch, which can lead to a lot
of services. This additional github workflow runs upon branch deletion and will delete the
created service

Cleanup Fastly Services upon branch deletion

---

README.md
src/index.js

allow `referrer` in addition to `referer`

feat(referer): both spelings of referrer are beautifull

---

README.md
src/coralogix-logger.js
src/google-logger.js
src/index.js

feat(checkpoints): add a new `checkpoint` data point

---

package-lock.json
package.json
src/index.js

- build(package): update js-compute dependency
- feat(index): add ability to collect data via GET request and `data` URL parameter

Add support for `GET/?data=` collection

---

src/index.js
test/post-deploy.test.js

feat(rum): generate ID for some get requests

---

src/coralogix-logger.js
src/google-logger.js
src/index.js

used to track parts of a page, such as embedded media

feat(rum): add target property

---

src/coralogix-logger.js
src/google-logger.js
src/index.js

this is the equivalent to `target` and specifies the element within the page that is the source of the tracked event

feat(index): support `source` property

---

.eslintrc.js
src/coralogix-error-logger.mjs
src/coralogix-logger.mjs
src/google-logger.mjs
src/index.mjs
src/utils.mjs
test/coralogix-error-logger.test.mjs
test/coralogix-logger.test.mjs
test/google-logger.test.mjs
test/utils.test.mjs

Also fixed the linter configuration to pick up .mjs files
Fixes: #192

feat(logger): protect privacy by masking timestamps

---

.circleci/config.yml
src/index.mjs
src/logger.mjs
test/post-deploy.test.js

- fix(index): allow empty string as id
- test(post-deploy): make sure empty id does not bomb anymore
- chore(debug): add some meta-logging
- chore: more console.log debugging
- refactor(logger): wait for import to complete
- ci(circleci): reduce wait time

Do not require IDs (allow empty string IDs)

---

src/coralogix-error-logger.mjs
src/coralogix-logger.mjs
src/google-logger.mjs
src/index.mjs
src/logger.mjs
src/utils.mjs
test/coralogix-error-logger.test.mjs
test/coralogix-logger.test.mjs
test/google-logger.test.mjs
test/post-deploy.test.js
test/utils.test.mjs

This reverts commit 68b82d973ed4cf48ea59260871754a57416240c2.

Try that again

---

src/coralogix-error-logger.mjs
src/index.mjs
src/logger.mjs
src/unpkg.mjs
test/google-logger.test.mjs
test/index.test.mjs
test/unpkg.test.mjs

Additional unit tests to increase coverage.
#190

Test coverage

---

src/unpkg.mjs
test/index.test.mjs
test/unpkg.test.mjs

Also added more unit tests.
Fixes: #206
Contributes to: #190

fix(unpkg): fix the cleaning of unpkg response headers

---

src/logger.mjs
test/index.test.mjs

test(cwv): ensure that TTFB core web vital works

---

src/utils.mjs
test/index.test.mjs
test/utils.test.mjs

fix(log): Limit time-padding value to 1 day

---

README.md

Just a commit to trigger a release which we want to happen to get the re-deployment via `hedy`

fix(fastly): Dummy commit to trigger a release

---

package-lock.json
package.json
src/index.mjs
test/index.test.mjs

To allow for selection of context-specific implementations at runtime
Also added /info.json endpoint to report basic runtime info, such as the currently serving platform.
Should pave the way for implementing #230
Fixes: #232

feat(context): expose context to main method

---

.circleci/config.yml
.gitignore
package-lock.json
package.json
src/utils.mjs
test/spider.test.mjs
tools/spider-list.js

Using the `IAB_SPIDER_LIST` available in the Project Helix CircleCI context, this PR will do two things:
1. convert the `IAB_SPIDER_LIST` into `src/spiders.mjs`, a very long `if` statement, almost long enough to be called AI
2. call this `isSpider` function with the user agent.
Through the build process, the complied spider list will be shipped in the build, even if it is (for copyright reasons) not part of the source code.

Detect Spiders and bots based on IAB bot list

---

.circleci/config.yml
package.json

Deploy to Cloudflare as part of the regular build

Cloudflare Deploy

---

src/console-logger.mjs
src/coralogix-error-logger.mjs
src/coralogix-logger.mjs
src/google-logger.mjs
src/utils.mjs
test/utils.test.mjs

feat(utils): Update extraction of hostname from X-Forwarded-Host to favour AEM hostname

---

src/console-logger.mjs
src/coralogix-error-logger.mjs
src/coralogix-logger.mjs
src/google-logger.mjs
src/utils.mjs
test/utils.test.mjs

feat(utils): Evaluate x-adobe-routing if set

---

src/coralogix-error-logger.mjs
src/coralogix-logger.mjs
test/coralogix-error-logger.test.mjs
test/coralogix-logger.test.mjs
test/index.test.mjs

see https://adobe-dx-support.slack.com/archives/C047RRVB4LV/p1707927822570399?thread_ts=1707900453.068369&cid=C047RRVB4LV
https://coralogix.com/docs/rest-api-singles/

feat(coralogix): support log format for new ingress endpoint in coralogix

---

src/console-logger.mjs
src/coralogix-error-logger.mjs
src/coralogix-logger.mjs
src/google-logger.mjs
src/utils.mjs
test/utils.test.mjs

Also extended unit tests to cover the changes.
Fixes: #287

fix(logger): support CloudFront-specific user-agent headers

---

src/coralogix-logger.mjs
test/coralogix-logger.test.mjs

- keep original user-agent
- Coralogix time is original time

feat: enhance Coralogix logs

---

src/utils.mjs
test/index.test.mjs
test/utils.test.mjs

- **test(utils): add test for chrome os**
- **test(utils): adjust chromeos name**
- **feat(utils): detect chromeos as desktop operating system**

Chrome OS Detection

---

src/utils.mjs

feat(checkpoints): enable paid and email checkpoints

---

src/utils.mjs

feat(checkpoints): enable cwv2 checkpoint

---

src/utils.mjs

fix(utils): drop unused variant checkpoint

---

src/coralogix-logger.mjs
src/google-logger.mjs
src/s3-logger.mjs
src/utils.mjs
test/coralogix-logger.test.mjs

- **fix(loggers): only log to consequential targets if weight is reasonable**
- **feat(coralogix): log unsupported checkpoints and unreasonable weights as warnings**

Sanitize Weight Parameter

---

src/coralogix-logger.mjs
src/google-logger.mjs
src/s3-logger.mjs
src/utils.mjs
test/google-logger.test.mjs
test/s3-logger.test.mjs
test/utils.test.mjs

fix: basic id validation

---

src/utils.mjs

fix: allow prerender checkpoint

---

src/utils.mjs

see https://cq-dev.slack.com/archives/C07198KKQ07/p1725350425871959

feat(utils): enable language checkpoint

---

src/utils.mjs

see https://cq-dev.slack.com/archives/C07198KKQ07/p1725446009159669

feat(utils): enable redirect checkpoint

---

src/cdnutils.mjs
test/post-deploy.test.mjs

see https://www.fastly.com/documentation/guides/concepts/compression/#dynamic-compression and https://cq-dev.slack.com/archives/C05QU7MMRNF/p1726098457786129

feat(cdn): enable compression on fastly

---

src/utils.mjs
test/utils.test.mjs

this goes hand in hand with https://github.com/adobe/helix-rum-js/pull/207

feat(utils): allow specifying the routing info via `routing` URL parameter

---

src/cdnutils.mjs
src/jsdelivr.mjs
src/unpkg.mjs
test/jsdelivr.test.mjs
test/unpkg.test.mjs

Even if these dir listings are a result of a redirect from the registry.

fix(packages): Prevent package registry dir listings 

---

src/bots.mjs

this adds two categories of bots: Compliance and Archive. No AI bots yet.

feat(bots): add more bots, based on 2024-10-31 data

---

.eslintrc.js
package-lock.json
package.json
src/utils.mjs
test/fixtures/user-agents.json
test/google-logger.test.mjs
test/index.test.mjs
test/s3-logger.test.mjs
test/utils.test.mjs

fix: include browser engines in user agent

---

src/utils.mjs

feat: enabling fill checkpoint.

---

src/index.mjs
test/index.test.mjs

fix(url): Disallow request URLs containing '..'

---

src/index.mjs
test/post-deploy.test.mjs

fix(url): Disallow encoded '..' and double encoded urls

---

src/coralogix-logger.mjs

fix(logging): adjust error severity level in Coralogix logger

---

.github/workflows/build.yml
package.json
src/index.mjs
test/index.test.mjs
test/post-deploy.test.mjs

- Changed the CORS response to return a status of 204 with a null body instead of a message.
- Added a test to verify that OPTIONS requests receive the correct CORS headers and status.

fix(response): update CORS response to use status 204 and null body

---

package-lock.json
package.json

This reverts commit b427583663c8c6652d1f74d2344953be15ee1364.

Revert "chore(deps): update adobe fixes (#480)"

---

src/utils.mjs

Removing `noscript` checkpoint per discussion in CPH

feat: remove noscript checkpoint

---

src/utils.mjs

chore(checkpoints): remove 'unsupported' checkpoint
