- src/index.js
- src/robots.js
- src/unpkg.js
- test/post-deploy.test.js
- feat: add robots.txt response
- fix(robots): use correct pathname for robots.txt
- feat(web-vitals): serve web-vitals module from rum collector
- fix(web-vitals): do not cache redirects forever
- feat(web-vitals): clean up response headers
The web vitals module is currently part of the helix boiler plate https://github.com/adobe/helix-project-boilerplate/tree/main/scripts and we would be better served by serving it directly from `/.rum/web-vitals...`
This PR adds the capability, with following features:
- https://helix-rum-collector-serve-through.hlx3.one/robots.txt discourages indexing of the domain
- https://helix-rum-collector-serve-through.hlx3.one/.rum/web-vitals@2.1.3/dist/web-vitals.base.js serves a specific version, with a "forever" cache setting (try 2.1.2, too)
- …
> Serve web vitals module

- src/google-logger.js
This is a small change, with a larger potential payoff:
@davidnuescheler and I spoke about https://github.com/adobe/helix-run-query/pull/612 (ability to auto-coarsen the granularity for low-traffic pages) and the undesirable effect it has on query execution time and cost (the fewer data there is, the longer and costlier the query gets) and what we can do to mitigate that effect.
One idea was to create separate tables for each customer, then use the Google BigQuery streaming insert API directly to update these tables. This is not practical because Google charges for streaming inserts in increments of 1 KB, so our tiny RUM update would be very costly.
Fortunately, Google BigQuery offers two features that help with our use case.
1. by partitioning data based on `time`(stamp), a separate data …
> feat(google): log to clustered table

- src/coralogix-logger.js
This will allow better alerts in Coralogix for client-side errors seen by RUM
> feat(coralogix): raise the severity of `checkpoint: error` to `error`

- .circleci/config.yml
- test/post-deploy.test.js
- ci(circleci): use a single service for CI deployments
- test(post-deploy): use a single hostname for post-deploy tests
This should simplify the CI setup a but and make it a bit more robust
> Simplify CI setup

- src/coralogix-error-logger.mjs
- src/coralogix-logger.mjs
- src/google-logger.mjs
- src/logger.mjs
It was left over in the specific logger impl files from before when the fastly:logger access was moved to logger.mjs
> fix(logger): move triple slash reference types to correct source file

- src/utils.mjs
- test/utils.test.mjs
By using the current second atop the current hour (dropping minutes and milliseconds) - only when the time padding is not set.
#192
> fix(logger): spread the timestamps a little when time padding is missing

- package-lock.json
- package.json
- src/console-logger.mjs
- src/index.mjs
- test/console-logger.test.mjs
- test/index.test.mjs
For Cloudflare logging, we just need to log to the console.
A typical log message to the console looks like this:
```
{"time":1701172800001,"host":"example.com","url":"https://somehost.somedomain.com/.rum/1","user_agent":"desktop","referer":null,"weight":2,"id":"id123","CLS":1,"LCP":1,"FID":4}
```
Fixes: #230
> feat(cloudflare): Support Cloudflare Logging

- src/cdnutils.mjs
- src/jsdelivr.mjs
- src/unpkg.mjs
- **refactor(cdn): extract cdn utils into separate module**
- **fix(jsdelivr): do not disclose path in 404 response**
> Refactor: apply same response cleanup to both CDN backends

- src/utils.mjs
- test/utils.test.mjs
These should not make it into regular URLs, but better get rid of them proactively
> fix(utils): strip away JWT tokens in paths

- src/utils.mjs
the URL implementation in cloudflare keeps an `@` for the username, even
if username and password have been emptied. This normalizes the behavior
> fix(cloudflare): clean up urls for real

- src/bots.mjs
- src/utils.mjs
- test/utils.test.mjs
- test(utils): add test for bot detection
- test(utils): add test for googlebot
- fix(utils): detect bots first, then mobile
- fix(bots): add bot detection for deepcrawl
> Classify mobile search/seo crawlers as bots

- package.json
- src/coralogix-logger.mjs
- src/google-logger.mjs
- src/index.mjs
- src/s3-logger.mjs
- src/utils.mjs
- test/index.test.mjs
- test/utils.test.mjs
Cloudflare truncates all log messages that exceed 16kb. This should normally not be a problem,
but in some cases we have seen truncation messages. This PR will apply a couple of tweaks to
the logged JSON object to keep size in check:
1. limit all string properties to 1024 characters
2. cast most CWVs to integers, as we don't need the fake accuracy nor the floating point length mismatches
- **feat(utils): add bloat control utility to ensure JSON strings don't get too long**
- **feat(logger): control bloat of JSON logs for Cloudflare**
> Bloat Control

- src/index.mjs
- test/index.test.mjs
FID has been removed as a Core Web Vital in April, this PR removes our ability to store it, even when posted
- **fix(cwv): remove deprecated FID**
- **test(index): do not expect invalid CWV values to come through anymore**
> Remove FID (outdated CWV)

- src/bots.mjs
- src/utils.mjs
- test/coralogix-error-logger.test.mjs
- test/fixtures/user-agents.json
- test/google-logger.test.mjs
Two adjustments:
1. added more classification precision (ie. `bot:search` instead of `bot`) to a handful of somewhat frequent user agents
2. changed the fallback device type classification from `desktop` to `undefined`
> feat: additional bot classification and adjust devicetype fallback

- src/cdnutils.mjs
- src/jsdelivr.mjs
- src/unpkg.mjs
- test/index.test.mjs
- test/jsdelivr.test.mjs
- test/post-deploy.test.mjs
- test/unpkg.test.mjs
Fixes: #483
Also ensures that `content-type: text/javascript` is always returned when serving javascript.
> fix(headers): cache-control header should never return null

- src/cdnutils.mjs
- src/index.mjs
- src/robots.mjs
- test/post-deploy.test.mjs
This update introduces the 'X-Frame-Options' header set to 'DENY' across various response functions to enhance security by preventing clickjacking attacks. The header is added to cleanupHeaders, cleanupResponse, prohibitDirectoryRequest, respondError, respondInfo, respondCORS, and robots.txt responses. Additionally, tests have been updated to verify the presence of this header in responses.
As none of the resources served by this service are of type text/html, there is no actual risk of click-jacking, so the addition of this header only serves the purpose of reducing the number of false-positive reports generated by overly simplistic security scanning software and their ill-configured reporting rules.
> feat(security): add X-Frame-Options header to responses

- src/console-logger.mjs
- src/google-logger.mjs
- src/privacy.js
- src/s3-logger.mjs
- src/utils.mjs
- test/google-logger.test.mjs
- test/index.test.mjs
- test/s3-logger.test.mjs
- test/utils.test.mjs
The current detection of PNRs is a bit overzealous. This PR adds checks for the telltale signs of machine-generated booking codes: high degree of randomness, hard to pronounce, letters mixed with numbers, all caps
It also fixes an issue with URL parameters being improperly stripped
- **fix: update URL handling in loggers to use cleanurl and add privacy.js for path sanitization**
- **feat: enhance privacy.js with PNR cleaning functionality and Shannon entropy calculation**
> More privacy filters

- src/utils.mjs
Removing `convert` checkpoint per discussion in CPH -- lightly used, not valued.
> feat: remove convert checkpoint

- src/utils.mjs
- test/utils.test.mjs
Introduces a new accessibility checkpoint.
The current expectation is that it will have:
- checkpoint: `a11y`
- source: `on` or `off`
- target: `undefined`
We can later potentially add granularity to the `target` to report accessibility levels.
Will be used by https://github.com/adobe/helix-rum-enhancer/pull/445
> feat(a11y): add support for a new accessibility checkpoint

- src/utils.mjs
- test/utils.test.mjs
Just adds support for `low`/`medium`/`high` sources as per https://github.com/adobe/helix-rum-enhancer/pull/456
> feat: allow the new a11y sources
